'use client';
import { useEffect, useRef, useState } from 'react';

type ScrollState = 'below' | 'visible' | 'above';

function useScrollReveal(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [state, setState] = useState<ScrollState>('below');

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setState('visible');
        } else {
          setState(entry.boundingClientRect.top > 0 ? 'below' : 'above');
        }
      },
      { threshold }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [threshold]);

  return { ref, state };
}

interface Feature {
  icon: string;
  title: string;
  body: string;
  tag?: string;
}

const FEATURES: Feature[] = [
  {
    icon: '📚',
    tag: 'Question Bank',
    title: '5,000+ exam-grade questions',
    body: 'Every question is modelled on real Oxbridge admission tests rather than textbook exercises. Physics, Maths, Chemistry, Biology. Multiple-choice with full worked solutions, generated by fine-tuned frontier models trained on thousands of actual past papers and the relevant syllabus.',
  },
  {
    icon: '🗂️',
    tag: 'Past Papers',
    title: 'All of NSAA, MAT, PAT — in one place',
    body: 'Access every multiple-choice question from every past NSAA, MAT, PAT, ENGAA and STEP paper. Timed exam mode or question-by-question practice. Every single answer has a full AI-generated worked solution.',
  },
  {
    icon: '🏆',
    tag: 'Olympiad Prep',
    title: 'Built for Olympiads too',
    body: "Trained on British Physics Olympiad, British Mathematical Olympiad and British Chemistry Olympiad material. Whether you're aiming for a gold medal or just want to stretch beyond A-level, OxAI has you covered.",
  },
  {
    icon: '🤖',
    tag: 'AI Tutor',
    title: 'A tutor that knows the syllabus inside out',
    body: "Ask the AI tutor anything mid-question. It reads your whiteboard, sees your working, and gives targeted hints without spoiling the answer. Like having a DPhil student in the room — without the hourly rate.",
  },
  {
    icon: '✏️',
    tag: 'Whiteboard',
    title: 'Sketch your working on screen',
    body: "The built-in whiteboard lets you draw, annotate, and work through problems naturally. Your tutor can see everything you've written and respond to your specific approach.",
  },
  {
    icon: '⚡',
    tag: 'Modes',
    title: 'Quick fire or past paper — your call',
    body: "Quick fire mode adapts to your weak spots, serving questions in a rapid-fire sequence until you've nailed each topic. Past paper mode replicates full exam conditions with the real papers, timed to the minute.",
  },
  {
    icon: '📈',
    tag: 'Generation',
    title: 'Unlimited on-demand questions',
    body: 'Need twenty thermodynamics questions at difficulty 4? Done in seconds. Generate any number of questions on any topic at any difficulty level — complete with diagrams, graphs, and tables where needed.',
  },
  {
    icon: '📄',
    tag: 'Export',
    title: 'Print your own exam paper',
    body: 'Export any session, topic set, or custom question batch to a clean PDF. Perfect for offline revision, taking to your tutor, or printing practice papers for the night before the exam.',
  },
];

// Group into pairs
const PAIRS = Array.from({ length: Math.ceil(FEATURES.length / 2) }, (_, i) =>
  FEATURES.slice(i * 2, i * 2 + 2)
);

function FeatureCard({ feature, side, state }: { feature: Feature; side: 'left' | 'right'; state: ScrollState }) {
  const offset = side === 'left' ? '-translate-x-16' : 'translate-x-16';
  const classes = [
    'transition-all duration-700 ease-out will-change-transform flex-1',
    state === 'visible' ? 'opacity-100 translate-x-0' : `opacity-0 ${offset}`,
  ].join(' ');

  return (
    <div className={classes}>
      <div className="w-20 h-20 rounded-2xl bg-accent-pale dark:bg-gray-800 flex items-center justify-center text-4xl shadow-sm mb-6">
        {feature.icon}
      </div>
      {feature.tag && (
        <div className="text-xs font-bold uppercase tracking-widest text-accent mb-2">
          {feature.tag}
        </div>
      )}
      <h3 className="text-2xl md:text-3xl font-black text-gray-900 dark:text-white leading-tight mb-4">
        {feature.title}
      </h3>
      <p className="text-base text-gray-500 dark:text-gray-400 leading-relaxed">
        {feature.body}
      </p>
    </div>
  );
}

function FeaturePair({ features }: { features: Feature[] }) {
  const { ref, state } = useScrollReveal(0.15);
  const [left, right] = features;

  return (
    <div className="min-h-[80vh] flex items-center py-20 px-6 md:px-16">
      <div ref={ref} className="max-w-5xl mx-auto w-full flex gap-12 md:gap-20 flex-col md:flex-row">
        <FeatureCard feature={left} side="left" state={state} />
        {right && <FeatureCard feature={right} side="right" state={state} />}
      </div>
    </div>
  );
}

export function ScrollFeatures() {
  return (
    <section className="relative bg-white dark:bg-gray-950 overflow-hidden">
      <div className="absolute left-1/2 top-0 bottom-0 w-px bg-gradient-to-b from-transparent via-accent/10 to-transparent pointer-events-none" />
      {PAIRS.map((pair) => (
        <FeaturePair key={pair[0].title} features={pair} />
      ))}
    </section>
  );
}
